server:
  port: 8080
  mode: debug

database:
  driver: postgres
  host: localhost
  port: 5432
  username: admin
  password: password
  db_name: go_admin
  sslmode: disable
  max_idle_conns: 10
  max_open_conns: 100

jwt:
  secret: your-secret-key-here
  expire: 24 # 小时
  issuer: go-admin

logger:
  level: info
  format: json
  output: stdout

s3:
  endpoint: http://localhost:9000
  access_key: root
  secret_key: 123456789

rabbitmq:
  host: localhost
  port: 5672
  username: admin
  password: 123456789
  vhost: /