// Code generated by ent, DO NOT EDIT.

package knowledgebase

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Sesame2/go-admin/internal/models/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldName, v))
}

// DatasetID applies equality check predicate on the "dataset_id" field. It's identical to DatasetIDEQ.
func DatasetID(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldDatasetID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldContainsFold(FieldName, v))
}

// DatasetIDEQ applies the EQ predicate on the "dataset_id" field.
func DatasetIDEQ(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldDatasetID, v))
}

// DatasetIDNEQ applies the NEQ predicate on the "dataset_id" field.
func DatasetIDNEQ(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldDatasetID, v))
}

// DatasetIDIn applies the In predicate on the "dataset_id" field.
func DatasetIDIn(vs ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldDatasetID, vs...))
}

// DatasetIDNotIn applies the NotIn predicate on the "dataset_id" field.
func DatasetIDNotIn(vs ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldDatasetID, vs...))
}

// DatasetIDGT applies the GT predicate on the "dataset_id" field.
func DatasetIDGT(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldDatasetID, v))
}

// DatasetIDGTE applies the GTE predicate on the "dataset_id" field.
func DatasetIDGTE(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldDatasetID, v))
}

// DatasetIDLT applies the LT predicate on the "dataset_id" field.
func DatasetIDLT(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldDatasetID, v))
}

// DatasetIDLTE applies the LTE predicate on the "dataset_id" field.
func DatasetIDLTE(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldDatasetID, v))
}

// DatasetIDContains applies the Contains predicate on the "dataset_id" field.
func DatasetIDContains(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldContains(FieldDatasetID, v))
}

// DatasetIDHasPrefix applies the HasPrefix predicate on the "dataset_id" field.
func DatasetIDHasPrefix(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldHasPrefix(FieldDatasetID, v))
}

// DatasetIDHasSuffix applies the HasSuffix predicate on the "dataset_id" field.
func DatasetIDHasSuffix(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldHasSuffix(FieldDatasetID, v))
}

// DatasetIDIsNil applies the IsNil predicate on the "dataset_id" field.
func DatasetIDIsNil() predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIsNull(FieldDatasetID))
}

// DatasetIDNotNil applies the NotNil predicate on the "dataset_id" field.
func DatasetIDNotNil() predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotNull(FieldDatasetID))
}

// DatasetIDEqualFold applies the EqualFold predicate on the "dataset_id" field.
func DatasetIDEqualFold(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEqualFold(FieldDatasetID, v))
}

// DatasetIDContainsFold applies the ContainsFold predicate on the "dataset_id" field.
func DatasetIDContainsFold(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldContainsFold(FieldDatasetID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.KnowledgeBase) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.KnowledgeBase) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.KnowledgeBase) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.NotPredicates(p))
}
