basePath: /api
host: localhost:8080
info:
  contact: {}
  description: 用于用户增删改查的 RESTful API
  title: 用户管理系统 API
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: 获取单个用户的信息
      produces:
      - application/json
      responses: {}
      summary: 获取用户信息
      tags:
      - 用户模块
swagger: "2.0"
