// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Sesame2/go-admin/internal/models/ent/knowledgebase"
	"github.com/google/uuid"
)

// KnowledgeBase is the model entity for the KnowledgeBase schema.
type KnowledgeBase struct {
	config `json:"-"`
	// ID of the ent.
	// 数据库ID
	ID uuid.UUID `json:"id":,omitempty`
	// 知识库名称
	Name string `json:"name,omitempty"`
	// 关丽娜的数据库ID
	DatasetID string `json:"dataset_id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更改时间
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*KnowledgeBase) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case knowledgebase.FieldName, knowledgebase.FieldDatasetID:
			values[i] = new(sql.NullString)
		case knowledgebase.FieldCreatedAt, knowledgebase.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case knowledgebase.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the KnowledgeBase fields.
func (kb *KnowledgeBase) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case knowledgebase.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				kb.ID = *value
			}
		case knowledgebase.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				kb.Name = value.String
			}
		case knowledgebase.FieldDatasetID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dataset_id", values[i])
			} else if value.Valid {
				kb.DatasetID = value.String
			}
		case knowledgebase.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				kb.CreatedAt = value.Time
			}
		case knowledgebase.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				kb.UpdatedAt = value.Time
			}
		default:
			kb.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the KnowledgeBase.
// This includes values selected through modifiers, order, etc.
func (kb *KnowledgeBase) Value(name string) (ent.Value, error) {
	return kb.selectValues.Get(name)
}

// Update returns a builder for updating this KnowledgeBase.
// Note that you need to call KnowledgeBase.Unwrap() before calling this method if this KnowledgeBase
// was returned from a transaction, and the transaction was committed or rolled back.
func (kb *KnowledgeBase) Update() *KnowledgeBaseUpdateOne {
	return NewKnowledgeBaseClient(kb.config).UpdateOne(kb)
}

// Unwrap unwraps the KnowledgeBase entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (kb *KnowledgeBase) Unwrap() *KnowledgeBase {
	_tx, ok := kb.config.driver.(*txDriver)
	if !ok {
		panic("ent: KnowledgeBase is not a transactional entity")
	}
	kb.config.driver = _tx.drv
	return kb
}

// String implements the fmt.Stringer.
func (kb *KnowledgeBase) String() string {
	var builder strings.Builder
	builder.WriteString("KnowledgeBase(")
	builder.WriteString(fmt.Sprintf("id=%v, ", kb.ID))
	builder.WriteString("name=")
	builder.WriteString(kb.Name)
	builder.WriteString(", ")
	builder.WriteString("dataset_id=")
	builder.WriteString(kb.DatasetID)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(kb.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(kb.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// KnowledgeBases is a parsable slice of KnowledgeBase.
type KnowledgeBases []*KnowledgeBase
