// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Sesame2/go-admin/internal/models/ent/knowledgebase"
	"github.com/google/uuid"
)

// KnowledgeBaseCreate is the builder for creating a KnowledgeBase entity.
type KnowledgeBaseCreate struct {
	config
	mutation *KnowledgeBaseMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (kbc *KnowledgeBaseCreate) SetName(s string) *KnowledgeBaseCreate {
	kbc.mutation.SetName(s)
	return kbc
}

// SetDatasetID sets the "dataset_id" field.
func (kbc *KnowledgeBaseCreate) SetDatasetID(s string) *KnowledgeBaseCreate {
	kbc.mutation.SetDatasetID(s)
	return kbc
}

// SetNillableDatasetID sets the "dataset_id" field if the given value is not nil.
func (kbc *KnowledgeBaseCreate) SetNillableDatasetID(s *string) *KnowledgeBaseCreate {
	if s != nil {
		kbc.SetDatasetID(*s)
	}
	return kbc
}

// SetCreatedAt sets the "created_at" field.
func (kbc *KnowledgeBaseCreate) SetCreatedAt(t time.Time) *KnowledgeBaseCreate {
	kbc.mutation.SetCreatedAt(t)
	return kbc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (kbc *KnowledgeBaseCreate) SetNillableCreatedAt(t *time.Time) *KnowledgeBaseCreate {
	if t != nil {
		kbc.SetCreatedAt(*t)
	}
	return kbc
}

// SetUpdatedAt sets the "updated_at" field.
func (kbc *KnowledgeBaseCreate) SetUpdatedAt(t time.Time) *KnowledgeBaseCreate {
	kbc.mutation.SetUpdatedAt(t)
	return kbc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (kbc *KnowledgeBaseCreate) SetNillableUpdatedAt(t *time.Time) *KnowledgeBaseCreate {
	if t != nil {
		kbc.SetUpdatedAt(*t)
	}
	return kbc
}

// SetID sets the "id" field.
func (kbc *KnowledgeBaseCreate) SetID(u uuid.UUID) *KnowledgeBaseCreate {
	kbc.mutation.SetID(u)
	return kbc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (kbc *KnowledgeBaseCreate) SetNillableID(u *uuid.UUID) *KnowledgeBaseCreate {
	if u != nil {
		kbc.SetID(*u)
	}
	return kbc
}

// Mutation returns the KnowledgeBaseMutation object of the builder.
func (kbc *KnowledgeBaseCreate) Mutation() *KnowledgeBaseMutation {
	return kbc.mutation
}

// Save creates the KnowledgeBase in the database.
func (kbc *KnowledgeBaseCreate) Save(ctx context.Context) (*KnowledgeBase, error) {
	kbc.defaults()
	return withHooks(ctx, kbc.sqlSave, kbc.mutation, kbc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (kbc *KnowledgeBaseCreate) SaveX(ctx context.Context) *KnowledgeBase {
	v, err := kbc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (kbc *KnowledgeBaseCreate) Exec(ctx context.Context) error {
	_, err := kbc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (kbc *KnowledgeBaseCreate) ExecX(ctx context.Context) {
	if err := kbc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (kbc *KnowledgeBaseCreate) defaults() {
	if _, ok := kbc.mutation.CreatedAt(); !ok {
		v := knowledgebase.DefaultCreatedAt()
		kbc.mutation.SetCreatedAt(v)
	}
	if _, ok := kbc.mutation.UpdatedAt(); !ok {
		v := knowledgebase.DefaultUpdatedAt()
		kbc.mutation.SetUpdatedAt(v)
	}
	if _, ok := kbc.mutation.ID(); !ok {
		v := knowledgebase.DefaultID()
		kbc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (kbc *KnowledgeBaseCreate) check() error {
	if _, ok := kbc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "KnowledgeBase.name"`)}
	}
	if v, ok := kbc.mutation.Name(); ok {
		if err := knowledgebase.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "KnowledgeBase.name": %w`, err)}
		}
	}
	if _, ok := kbc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "KnowledgeBase.created_at"`)}
	}
	if _, ok := kbc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "KnowledgeBase.updated_at"`)}
	}
	return nil
}

func (kbc *KnowledgeBaseCreate) sqlSave(ctx context.Context) (*KnowledgeBase, error) {
	if err := kbc.check(); err != nil {
		return nil, err
	}
	_node, _spec := kbc.createSpec()
	if err := sqlgraph.CreateNode(ctx, kbc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	kbc.mutation.id = &_node.ID
	kbc.mutation.done = true
	return _node, nil
}

func (kbc *KnowledgeBaseCreate) createSpec() (*KnowledgeBase, *sqlgraph.CreateSpec) {
	var (
		_node = &KnowledgeBase{config: kbc.config}
		_spec = sqlgraph.NewCreateSpec(knowledgebase.Table, sqlgraph.NewFieldSpec(knowledgebase.FieldID, field.TypeUUID))
	)
	if id, ok := kbc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := kbc.mutation.Name(); ok {
		_spec.SetField(knowledgebase.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := kbc.mutation.DatasetID(); ok {
		_spec.SetField(knowledgebase.FieldDatasetID, field.TypeString, value)
		_node.DatasetID = value
	}
	if value, ok := kbc.mutation.CreatedAt(); ok {
		_spec.SetField(knowledgebase.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := kbc.mutation.UpdatedAt(); ok {
		_spec.SetField(knowledgebase.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// KnowledgeBaseCreateBulk is the builder for creating many KnowledgeBase entities in bulk.
type KnowledgeBaseCreateBulk struct {
	config
	err      error
	builders []*KnowledgeBaseCreate
}

// Save creates the KnowledgeBase entities in the database.
func (kbcb *KnowledgeBaseCreateBulk) Save(ctx context.Context) ([]*KnowledgeBase, error) {
	if kbcb.err != nil {
		return nil, kbcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(kbcb.builders))
	nodes := make([]*KnowledgeBase, len(kbcb.builders))
	mutators := make([]Mutator, len(kbcb.builders))
	for i := range kbcb.builders {
		func(i int, root context.Context) {
			builder := kbcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*KnowledgeBaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, kbcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, kbcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, kbcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (kbcb *KnowledgeBaseCreateBulk) SaveX(ctx context.Context) []*KnowledgeBase {
	v, err := kbcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (kbcb *KnowledgeBaseCreateBulk) Exec(ctx context.Context) error {
	_, err := kbcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (kbcb *KnowledgeBaseCreateBulk) ExecX(ctx context.Context) {
	if err := kbcb.Exec(ctx); err != nil {
		panic(err)
	}
}
