// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Sesame2/go-admin/internal/models/ent/knowledgebase"
	"github.com/Sesame2/go-admin/internal/models/ent/predicate"
)

// KnowledgeBaseUpdate is the builder for updating KnowledgeBase entities.
type KnowledgeBaseUpdate struct {
	config
	hooks    []Hook
	mutation *KnowledgeBaseMutation
}

// Where appends a list predicates to the KnowledgeBaseUpdate builder.
func (kbu *KnowledgeBaseUpdate) Where(ps ...predicate.KnowledgeBase) *KnowledgeBaseUpdate {
	kbu.mutation.Where(ps...)
	return kbu
}

// SetName sets the "name" field.
func (kbu *KnowledgeBaseUpdate) SetName(s string) *KnowledgeBaseUpdate {
	kbu.mutation.SetName(s)
	return kbu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (kbu *KnowledgeBaseUpdate) SetNillableName(s *string) *KnowledgeBaseUpdate {
	if s != nil {
		kbu.SetName(*s)
	}
	return kbu
}

// SetDatasetID sets the "dataset_id" field.
func (kbu *KnowledgeBaseUpdate) SetDatasetID(s string) *KnowledgeBaseUpdate {
	kbu.mutation.SetDatasetID(s)
	return kbu
}

// SetNillableDatasetID sets the "dataset_id" field if the given value is not nil.
func (kbu *KnowledgeBaseUpdate) SetNillableDatasetID(s *string) *KnowledgeBaseUpdate {
	if s != nil {
		kbu.SetDatasetID(*s)
	}
	return kbu
}

// ClearDatasetID clears the value of the "dataset_id" field.
func (kbu *KnowledgeBaseUpdate) ClearDatasetID() *KnowledgeBaseUpdate {
	kbu.mutation.ClearDatasetID()
	return kbu
}

// SetUpdatedAt sets the "updated_at" field.
func (kbu *KnowledgeBaseUpdate) SetUpdatedAt(t time.Time) *KnowledgeBaseUpdate {
	kbu.mutation.SetUpdatedAt(t)
	return kbu
}

// Mutation returns the KnowledgeBaseMutation object of the builder.
func (kbu *KnowledgeBaseUpdate) Mutation() *KnowledgeBaseMutation {
	return kbu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (kbu *KnowledgeBaseUpdate) Save(ctx context.Context) (int, error) {
	kbu.defaults()
	return withHooks(ctx, kbu.sqlSave, kbu.mutation, kbu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (kbu *KnowledgeBaseUpdate) SaveX(ctx context.Context) int {
	affected, err := kbu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (kbu *KnowledgeBaseUpdate) Exec(ctx context.Context) error {
	_, err := kbu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (kbu *KnowledgeBaseUpdate) ExecX(ctx context.Context) {
	if err := kbu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (kbu *KnowledgeBaseUpdate) defaults() {
	if _, ok := kbu.mutation.UpdatedAt(); !ok {
		v := knowledgebase.UpdateDefaultUpdatedAt()
		kbu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (kbu *KnowledgeBaseUpdate) check() error {
	if v, ok := kbu.mutation.Name(); ok {
		if err := knowledgebase.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "KnowledgeBase.name": %w`, err)}
		}
	}
	return nil
}

func (kbu *KnowledgeBaseUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := kbu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(knowledgebase.Table, knowledgebase.Columns, sqlgraph.NewFieldSpec(knowledgebase.FieldID, field.TypeUUID))
	if ps := kbu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := kbu.mutation.Name(); ok {
		_spec.SetField(knowledgebase.FieldName, field.TypeString, value)
	}
	if value, ok := kbu.mutation.DatasetID(); ok {
		_spec.SetField(knowledgebase.FieldDatasetID, field.TypeString, value)
	}
	if kbu.mutation.DatasetIDCleared() {
		_spec.ClearField(knowledgebase.FieldDatasetID, field.TypeString)
	}
	if value, ok := kbu.mutation.UpdatedAt(); ok {
		_spec.SetField(knowledgebase.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, kbu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{knowledgebase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	kbu.mutation.done = true
	return n, nil
}

// KnowledgeBaseUpdateOne is the builder for updating a single KnowledgeBase entity.
type KnowledgeBaseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KnowledgeBaseMutation
}

// SetName sets the "name" field.
func (kbuo *KnowledgeBaseUpdateOne) SetName(s string) *KnowledgeBaseUpdateOne {
	kbuo.mutation.SetName(s)
	return kbuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (kbuo *KnowledgeBaseUpdateOne) SetNillableName(s *string) *KnowledgeBaseUpdateOne {
	if s != nil {
		kbuo.SetName(*s)
	}
	return kbuo
}

// SetDatasetID sets the "dataset_id" field.
func (kbuo *KnowledgeBaseUpdateOne) SetDatasetID(s string) *KnowledgeBaseUpdateOne {
	kbuo.mutation.SetDatasetID(s)
	return kbuo
}

// SetNillableDatasetID sets the "dataset_id" field if the given value is not nil.
func (kbuo *KnowledgeBaseUpdateOne) SetNillableDatasetID(s *string) *KnowledgeBaseUpdateOne {
	if s != nil {
		kbuo.SetDatasetID(*s)
	}
	return kbuo
}

// ClearDatasetID clears the value of the "dataset_id" field.
func (kbuo *KnowledgeBaseUpdateOne) ClearDatasetID() *KnowledgeBaseUpdateOne {
	kbuo.mutation.ClearDatasetID()
	return kbuo
}

// SetUpdatedAt sets the "updated_at" field.
func (kbuo *KnowledgeBaseUpdateOne) SetUpdatedAt(t time.Time) *KnowledgeBaseUpdateOne {
	kbuo.mutation.SetUpdatedAt(t)
	return kbuo
}

// Mutation returns the KnowledgeBaseMutation object of the builder.
func (kbuo *KnowledgeBaseUpdateOne) Mutation() *KnowledgeBaseMutation {
	return kbuo.mutation
}

// Where appends a list predicates to the KnowledgeBaseUpdate builder.
func (kbuo *KnowledgeBaseUpdateOne) Where(ps ...predicate.KnowledgeBase) *KnowledgeBaseUpdateOne {
	kbuo.mutation.Where(ps...)
	return kbuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (kbuo *KnowledgeBaseUpdateOne) Select(field string, fields ...string) *KnowledgeBaseUpdateOne {
	kbuo.fields = append([]string{field}, fields...)
	return kbuo
}

// Save executes the query and returns the updated KnowledgeBase entity.
func (kbuo *KnowledgeBaseUpdateOne) Save(ctx context.Context) (*KnowledgeBase, error) {
	kbuo.defaults()
	return withHooks(ctx, kbuo.sqlSave, kbuo.mutation, kbuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (kbuo *KnowledgeBaseUpdateOne) SaveX(ctx context.Context) *KnowledgeBase {
	node, err := kbuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (kbuo *KnowledgeBaseUpdateOne) Exec(ctx context.Context) error {
	_, err := kbuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (kbuo *KnowledgeBaseUpdateOne) ExecX(ctx context.Context) {
	if err := kbuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (kbuo *KnowledgeBaseUpdateOne) defaults() {
	if _, ok := kbuo.mutation.UpdatedAt(); !ok {
		v := knowledgebase.UpdateDefaultUpdatedAt()
		kbuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (kbuo *KnowledgeBaseUpdateOne) check() error {
	if v, ok := kbuo.mutation.Name(); ok {
		if err := knowledgebase.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "KnowledgeBase.name": %w`, err)}
		}
	}
	return nil
}

func (kbuo *KnowledgeBaseUpdateOne) sqlSave(ctx context.Context) (_node *KnowledgeBase, err error) {
	if err := kbuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(knowledgebase.Table, knowledgebase.Columns, sqlgraph.NewFieldSpec(knowledgebase.FieldID, field.TypeUUID))
	id, ok := kbuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KnowledgeBase.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := kbuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, knowledgebase.FieldID)
		for _, f := range fields {
			if !knowledgebase.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != knowledgebase.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := kbuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := kbuo.mutation.Name(); ok {
		_spec.SetField(knowledgebase.FieldName, field.TypeString, value)
	}
	if value, ok := kbuo.mutation.DatasetID(); ok {
		_spec.SetField(knowledgebase.FieldDatasetID, field.TypeString, value)
	}
	if kbuo.mutation.DatasetIDCleared() {
		_spec.ClearField(knowledgebase.FieldDatasetID, field.TypeString)
	}
	if value, ok := kbuo.mutation.UpdatedAt(); ok {
		_spec.SetField(knowledgebase.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &KnowledgeBase{config: kbuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, kbuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{knowledgebase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	kbuo.mutation.done = true
	return _node, nil
}
